### PR TITLE
[WIP] Updated to adapter 0.2 and tagging 0.3

### PR DESCRIPTION
**Pull request by Nyholm**
Integration tests passes but the doctrine specific tests are failing. @aequasi have a look if you like.

### CODE REVIEW

**Comment by cryptiklemur** [comment]
:+1:

**Comment by Nyholm** [comment]
The DoctrineAdapter was the first adapter we wrote and the test class was the first tests. Are these really needed with the integration tests in place? 
I do not think so. What do you think?

**Comment by cryptiklemur** [comment]
Agreed, Just need to get that 15% back in integration tests

**Comment by Nyholm** [comment]
Oh, I missed that the coverage dropped. I guess we need some more tests then. I've updated the PR

**Pull request merged**
